name: Command Mode Formatting
on:
  issue_comment:
    types: [created]
jobs:
  apply-formatting:
    name: Format Py and C++ Code
    runs-on: ubuntu-latest
    if: startsWith(github.event.comment.body, '@par-hermes format')
    steps:
    - uses: JoshuaSBrown/cpp-py-formatter/command@v0.3.0
      with:
        botName: par-hermes
        clangFormatVersion: 11
        token: ${{ secrets.GITHUB_TOKEN }}
